name: Build Milk Tracker and Deploy to local

on:
  push:
    branches: [self-hosted]

jobs:
  build-deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client  # key setting
    steps:
      - uses: actions/checkout@v3

      - name: Install deps & build
        run: |
          npm ci
          npm run build

      - name: Deploy to Server
        run: |
          rm -rf /var/www/milk-tracker/*
          cp -r dist/* /var/www/milk-tracker/